"""
Lesson 43 - Step 2: Outcomes After Random Assignment
====================================================
THE RECIPE
Start from experimental_design_01_factor_randomization.py, then introduce:
    1. randomized_outcomes()   cycle times after random assignment
    2. group_summaries()       mean experience and mean cycle time by method
    3. save_figure()           boxplots of the randomized experiment

Context:
The same 36 stations are rebuilt from seed 42. No earlier lesson script is
imported. Random assignment is what makes a later mean difference a treatment
comparison rather than a who-chose-what comparison. In this step, we simulate
the actual outcome (cycle time) which is influenced by a baseline, the
treatment effect, experience, and random noise.

How to read this file:
This file models the data-generating process for an experiment. We define the
"true" effects of our treatments (Standard = 0, Guided = -2, Automated = -7).
Because we randomized, the observed difference in means will be an unbiased
estimate of these true effects. In OOP terms, we are instantiating units with
their "true" properties and observing the result of an applied method.

Run it:
    uv run en/L43_Experimental_Design_Principles/src/experimental_design_02_randomized_outcomes.py
"""

# Standard library imports for path manipulation
from pathlib import Path

# Third-party imports for data manipulation and visualization
import matplotlib
import numpy as np
import pandas as pd

# Use the 'Agg' backend for matplotlib to generate plots without a display
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Constants to control the synthetic data generation
SEED = 42  # Seed for reproducibility
N_UNITS = 36  # Total number of stations
N_PER_GROUP = 12  # Number of stations per treatment
TREATMENTS = ("Standard", "Guided", "Automated")  # Experimental factor levels
BASE_MEAN = 52.0  # Base cycle time in seconds without any effects
# True causal effects for each treatment (reduction in cycle time)
EFFECTS = {"Standard": 0.0, "Guided": -2.0, "Automated": -7.0}
# How much cycle time decreases per year of experience above the mean
EXPERIENCE_SLOPE = -0.35
# Standard deviation of the random noise in cycle time
NOISE_SIGMA = 2.4
# Directory to save generated figures
DIR_FIGURES = Path(__file__).resolve().parent.parent / "figures"
DIR_FIGURES.mkdir(parents=True, exist_ok=True)


def build_randomized_experiment(seed: int = SEED) -> pd.DataFrame:
    """Rebuild stations, random assignment, and cycle times from seed 42.

    Parameters
    ----------
    seed : int, optional
        Random seed for data generation, by default SEED.

    Returns
    -------
    pd.DataFrame
        A DataFrame representing the complete experiment, including covariates,
        assignments, and the final observed outcomes.

    Notes
    -----
    This function simulates the 'data generating process'. The final cycle time
    is a linear combination of the baseline mean, the true treatment effect,
    the effect of the operator's experience, and random noise.
    """
    rng = np.random.default_rng(seed)

    # Generate pretreatment covariate (experience)
    experience = rng.uniform(1.0, 9.0, N_UNITS)

    # Randomly assign treatments
    labels = np.repeat(np.array(TREATMENTS), N_PER_GROUP)
    rng.shuffle(labels)

    # Generate random noise for the outcome
    noise = rng.normal(0.0, NOISE_SIGMA, N_UNITS)

    # Map the assigned treatments to their true effects
    effect = np.array([EFFECTS[name] for name in labels])

    # Calculate the simulated outcome (cycle time)
    cycle_time = (
        BASE_MEAN
        + effect
        + EXPERIENCE_SLOPE * (experience - experience.mean())
        + noise
    )

    # Return the assembled dataset
    return pd.DataFrame(
        {
            "station_id": np.arange(1, N_UNITS + 1),
            "experience_years": experience,
            "method": labels,
            "cycle_time_seconds": cycle_time,
        }
    )


# --- NEW (1) randomized_outcomes() -------------------------------------------
def randomized_outcomes(experiment: pd.DataFrame) -> pd.DataFrame:
    """Return the randomized experiment with the cycle-time response.

    Parameters
    ----------
    experiment : pd.DataFrame
        The full experimental dataset generated by build_randomized_experiment.

    Returns
    -------
    pd.DataFrame
        A copy of the dataset containing the randomized outcomes.

    Notes
    -----
    In a real scenario, this is where we would join the pretreatment data with
    the post-treatment observed results. Here we just return a copy of our
    simulated data.
    """
    return experiment.copy()
# ------------------------------------------------------------------------------


# --- NEW (2) group_summaries() -----------------------------------------------
def group_summaries(experiment: pd.DataFrame) -> pd.DataFrame:
    """Summarize experience and cycle time by randomly assigned method.

    Parameters
    ----------
    experiment : pd.DataFrame
        The dataset containing assignments and outcomes.

    Returns
    -------
    pd.DataFrame
        A summary DataFrame with count, mean experience, and mean/sd cycle time
        for each treatment group.

    Notes
    -----
    Aggregation is a standard way to estimate the average treatment effect.
    By comparing the group means, we can see if the treatments had an impact.
    """
    rows = []
    # Iterate through each treatment level
    for name in TREATMENTS:
        # Filter the dataset for the current treatment
        block = experiment.loc[experiment["method"] == name]
        rows.append(
            {
                "method": name,
                "n": int(len(block)),
                "mean_experience": float(block["experience_years"].mean()),
                "mean_cycle_time": float(block["cycle_time_seconds"].mean()),
                "sd_cycle_time": float(block["cycle_time_seconds"].std(ddof=1)),
            }
        )
    return pd.DataFrame(rows)
# ------------------------------------------------------------------------------


# --- NEW (3) save_figure() ---------------------------------------------------
def save_figure(experiment: pd.DataFrame) -> Path:
    """Save cycle-time boxplots for the randomized packing-method factor.

    Parameters
    ----------
    experiment : pd.DataFrame
        The dataset containing assignments and outcomes.

    Returns
    -------
    Path
        The file path where the visualization was saved.

    Notes
    -----
    Visualizing the outcomes helps us see both the shift in the median/mean
    and the variance within each treatment group.
    """
    output_path = DIR_FIGURES / "experimental_design_02_randomized_outcomes.png"
    colors = ["#1A2E51", "#5B8DEF", "#EC2661"]

    # Extract the cycle time values for each group
    groups = [
        experiment.loc[
            experiment["method"] == name, "cycle_time_seconds"
        ].to_numpy()
        for name in TREATMENTS
    ]
    # Calculate the mean for each group to plot later
    means = [float(np.mean(values)) for values in groups]

    # Create the figure
    fig, ax = plt.subplots(figsize=(8.4, 4.6))

    # Draw the boxplots
    boxes = ax.boxplot(
        groups,
        positions=[1, 2, 3],
        patch_artist=True,
        widths=0.58,
        medianprops={"color": "#1A2E51", "linewidth": 1.6},
    )
    # Apply colors
    for patch, color in zip(boxes["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.45)

    # Overlay the means as distinct scatter points
    ax.scatter([1, 2, 3], means, color="#EC2661", zorder=3, label="Group mean")

    # Format the axes and labels
    ax.set_xticks([1, 2, 3])
    ax.set_xticklabels(TREATMENTS)
    ax.set_ylabel("Cycle time (seconds)")
    ax.set_title("Randomized Experiment: Cycle Time by Packing Method")
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    ax.legend(frameon=False)

    # Save the figure
    fig.tight_layout()
    fig.savefig(output_path, dpi=170)
    plt.close(fig)
    return output_path
# ------------------------------------------------------------------------------


def main() -> None:
    # 1. Build and retrieve the randomized outcomes
    experiment = randomized_outcomes(build_randomized_experiment())
    # 2. Summarize the data by group
    summary = group_summaries(experiment)
    # 3. Create the visualization
    figure_path = save_figure(experiment)

    # Calculate the observed difference between Automated and Standard
    auto_minus_std = (
        float(summary.loc[summary["method"] == "Automated", "mean_cycle_time"].iloc[0])
        - float(summary.loc[summary["method"] == "Standard", "mean_cycle_time"].iloc[0])
    )

    # Print the report
    print("================================================================")
    print("LESSON 43 - STEP 2: RANDOMIZED OUTCOMES")
    print("================================================================")
    print("Synthetic data notice           : No real company data are used")
    print(f"Random seed                     : {SEED}")
    print(f"True Automated effect (seconds) : {EFFECTS['Automated']:.1f}")

    # Print the row summaries
    for _, row in summary.iterrows():
        print(
            f"n, mean Y, mean experience ({row['method']:<10}): "
            f"{int(row['n']):>2}, {row['mean_cycle_time']:.6f}, "
            f"{row['mean_experience']:.6f}"
        )
    print(f"Randomized Auto-Standard gap    : {auto_minus_std:.6f}")
    print(f"Figure saved to                 : {figure_path}")
    print("================================================================")


if __name__ == "__main__":
    main()

